function noReturn(a : number) {
	writeString("empty function");
}

function noReturnVoid(beta : number, isSomething : boolean, some32String : string): void {
	writeString("empty function");
}

function withReturn(i_0 : boolean, i_1 : boolean, i_2 : boolean, i_3[] : number) {
    return;
}

function returnVoid(stringArray[] : string): void {
    return;
}

function start(): void {
	writeString("empty function");
}